### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by samtstern**
Move to `expect-firestore` 1.0 and do associated cleanup.

### CODE REVIEW

**Comment by samtstern** [comment]
Remaining failure:

```
  1) [RBAC Rules]
       [step2] owners can create stories:
     Error: Error: firestore.rules line [11], column [18]. Null value error.
      at Object.assert (node_modules/expect-firestore/lib/assert.js:22:15)
      at Object.<anonymous> (dist/test.js:116:25)
      at Generator.next (<anonymous>)
      at fulfilled (dist/test.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:109
```

**Comment by samtstern** [comment]
This failure will be fixed by this PR:
https://github.com/GitbookIO/expect-firestore/pull/13

**Comment by SamyPesse** [comment]
@samtstern I've published `expect-firestore@1.0.1` with GitbookIO/expect-firestore#13

**Comment by samtstern** [comment]
@SamyPesse thanks!

**Pull request merged**
